### PR TITLE
Add irods 4.3.0 recipe

### PR DESCRIPTION
**Pull request by mksanger**
Also add updated dependency recipes:
avrocpp
boost
catch2
json
libarchive

### CODE REVIEW

**Comment by kjsanger** [comment]
Looks like it's failing to build - missing boost library?

**Comment by mksanger** [comment]
I think its because I didn't tell it to build a version of any of the dependencies for the new irods

**Comment by mksanger** [comment]
While building baton with irods 4.3.0
```
ERROR:root:./configure: line 8419: /usr/bin/file: No such file or directory
ERROR:root:configure: WARNING: unable to find sphinx-build on this system;
ERROR:root:                  the HTML manual and manpage will not be created
ERROR:root:configure: error: unable to find libirods_common
ERROR:root:Traceback (most recent call last):
ERROR:root:  File "/opt/conda/bin/conda-build", line 11, in <module>
```

**Comment by kjsanger** [comment]
As we're moving away from Conda, we can close this.

**Pull request closed without merging**
