### PR TITLE
iRODS 4.2 packages

### PR DESCRIPTION
**Pull request by dkj**
Built on @mp15 's  #146 
Works in our Docker dependency isolation containers.
Needs `conda-forge` and a repo with gzip e.g. `ostrokach`
Is ~a bit of a mess~ as good as it's going to get in the very short term...

### CODE REVIEW

**Comment by dkj** [comment]
Biobambam2 not building - suspect depenencies and libmaus build may not be right (no sign of iRODS dynamic library I expect for 4.2)

**Comment by dkj** [comment]
missing `libarchive` dependency for `irods-runtime`

**Comment by mgcam** [comment]
I deployed tools which were built using these recipes into a prod-style NPG hierarchy and performed very simple tests for some of them. Problems might come up when we use tools in anger, but for that they have to be deployed to start with.

**Comment by mgcam** [comment]
A MiSeq run is loaded to iRODS 4.2.7 using these tools and a Perl stack linked to them

**Pull request merged**
